# Holding Office Hours {.unnumbered}

Another one of the TA's responsibilities is to hold weekly office hours. You will need to be available for student drop-ins at least one hour a week. You will also need to be available to meet with students at other times outside of your office hours for individual appointments. These individual appointment times are initiated by the students contacting you and arranging a mutual agreed upon time to meet. These appointments may be in-person or happen over Zoom, depending on what you and the student decide.

We allow students from any section (not just the one you are TAing for) to come to any TA's office hours. As such, when you are deciding the time of your set weekly office hours, it is important to make sure that your office hours do not overlap with any of the sections of EPsy 3264. (Find the times for the 3264 classes [here](https://dept.aem.umn.edu/cgi-bin/courses/noauth/class-schedule?next=EPSY).) We also try to make sure that there are many times available, so we try not to have your office hours overlap with other TAs' or instructors' office hours. 


::: {.callout-important}
You need to communicate the time and location of your office hours to the entire EPsy 3264 instructional team.
:::


