# Grading Student Work {.unnumbered}

Another TA responsibility is to grade student work (group quizzes and individual exams). Some instructors may do some grading, but this is a conversation that needs to take place with the instructor you are grading for. You also may need to enter scores in Canvas and a course spreadsheet. Again, the instructor you are grading for may have more specific instructions for you.

**The answer keys and rubrics for the assessments are located in the shared EPsy 3264 Google Drive.**

Grading needs to be done in a timely manner. This is important for providing feedback to students so they can incorporate it into their next assessment.

- If the exam or quiz comes in on the first class day of the week, we ideally want you to have the assessments graded and ready to returned to students by the second class day of the week. 
- If the exam comes in on the second class day of the week, you need to have the assessments graded and returned to students by the next class period.

If this is not possible, please let the instructor know and also communicate when you will have the grading completed.  



